import './styles/globals.css'

import type { Metadata } from 'next'
import { Lobster, Noto_Sans, Source_Sans_3 } from 'next/font/google'
import { JSX } from 'react'

import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { Navigation } from '@/components/Navigation'

import Provider from './provider'

export const sourceSans = Source_Sans_3({
  variable: '--font-source-sans',
  subsets: ['latin'],
})

export const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
})

export const lobster = Lobster({
  variable: '--font-lobster',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Next.js Server Component Scaffold',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="manifest" href="/app.webmanifest" />
        <link rel="icon" type="image/x-icon" sizes="48x48" href="/favicons/favicon.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png" />
        <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="canonical" href="https://example.com" />
      </head>
      <body className={`${sourceSans.variable} ${notoSans.variable} ${lobster.variable} antialiased`}>
        <Provider>
          <div className="font-source-sans font-noto-sans flex flex-col w-full min-h-[100vh] min-h-fill-available pt-[50px] px-0 pb-[20px]">
            <header className="w-full pb-[40px]">
              <Header />
            </header>
            <nav className="pb-[10px]">
              <Navigation />
            </nav>
            <main className="flex flex-1 flex-col items-center justify-center w-full bg-[url('/images/logo.webp')] bg-no-repeat bg-position-[80%_center] bg-size-[25%_auto]">
              {children}
            </main>
            <footer className="flex items-center justify-center w-full">
              <Footer />
            </footer>
          </div>
        </Provider>
      </body>
    </html>
  )
}
